# Generated by Django 5.2.7 on 2025-11-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plants/')),
                ('prediction_name', models.CharField(max_length=100)),
                ('disease_name', models.CharField(blank=True, max_length=100, null=True)),
                ('prescription', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
